"""Add advanced department permissions

Revision ID: 01af1f446ce7
Revises: 43bbd593ac0b
Create Date: 2025-08-04 18:28:08.653409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01af1f446ce7'
down_revision = '43bbd593ac0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_created_at'))
        batch_op.drop_index(batch_op.f('ix_classes_end_time'))
        batch_op.drop_index(batch_op.f('ix_classes_scheduled_date_time'))
        batch_op.drop_index(batch_op.f('ix_classes_status'))
        batch_op.drop_index(batch_op.f('ix_classes_tutor_date'))
        batch_op.drop_index(batch_op.f('ix_classes_tutor_id'))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('restricted_permissions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('restricted_permissions')
        batch_op.drop_column('permission_level')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_tutor_id'), ['tutor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_tutor_date'), ['tutor_id', 'scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_scheduled_date_time'), ['scheduled_date', 'scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
