"""Add course end date to students

Revision ID: 0bcff3bda4f1
Revises: dd0ae655d478
Create Date: 2025-07-24 16:42:04.007063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcff3bda4f1'
down_revision = 'dd0ae655d478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('batch_identifier', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('course_duration_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('course_duration_months')
        batch_op.drop_column('batch_identifier')
        batch_op.drop_column('course_end_date')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
