"""Add graduation and drop tables

Revision ID: 0be6d56ecb1f
Revises: 01af1f446ce7
Create Date: 2025-08-21 17:26:05.579984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be6d56ecb1f'
down_revision = '01af1f446ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_completion_status'), ['completion_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_primary_student_id'), ['primary_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_scheduled_date'), ['scheduled_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_tutor_id'), ['tutor_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['quality_reviewed_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['attendance_verified_by'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_enrollment_status'), ['enrollment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_is_active'))
        batch_op.drop_index(batch_op.f('ix_students_enrollment_status'))
        batch_op.drop_index(batch_op.f('ix_students_created_at'))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classes_tutor_id'))
        batch_op.drop_index(batch_op.f('ix_classes_status'))
        batch_op.drop_index(batch_op.f('ix_classes_scheduled_time'))
        batch_op.drop_index(batch_op.f('ix_classes_scheduled_date'))
        batch_op.drop_index(batch_op.f('ix_classes_primary_student_id'))
        batch_op.drop_index(batch_op.f('ix_classes_completion_status'))

    # ### end Alembic commands ###
