"""Add reschedule request system

Revision ID: 2ec304ea383f
Revises: 0bcff3bda4f1
Create Date: 2025-07-26 14:55:45.751791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec304ea383f'
down_revision = '0bcff3bda4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reschedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('original_time', sa.Time(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('requested_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('has_conflicts', sa.Boolean(), nullable=True),
    sa.Column('conflict_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for better performance
    op.create_index('ix_reschedule_requests_status', 'reschedule_requests', ['status'])
    op.create_index('ix_reschedule_requests_class_id', 'reschedule_requests', ['class_id'])
    op.create_index('ix_reschedule_requests_requested_by', 'reschedule_requests', ['requested_by'])
    op.create_index('ix_reschedule_requests_request_date', 'reschedule_requests', ['request_date'])
    
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reschedule_requests_request_date', table_name='reschedule_requests')
    op.drop_index('ix_reschedule_requests_requested_by', table_name='reschedule_requests')
    op.drop_index('ix_reschedule_requests_class_id', table_name='reschedule_requests')
    op.drop_index('ix_reschedule_requests_status', table_name='reschedule_requests')
    op.drop_table('reschedule_requests')