"""Fix missing demo_student_id column

Revision ID: 3f7a3eafc2ba
Revises: ac9c1c5bec4b
Create Date: 2025-07-12 19:13:54.630304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7a3eafc2ba'
down_revision = '7d93bede49a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo_student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'demo_students', ['demo_student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('demo_student_id')

    # ### end Alembic commands ###
