"""Add batch_id to Class

Revision ID: 43bbd593ac0b
Revises: fcd73b904434
Create Date: 2025-07-26 16:05:41.614701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bbd593ac0b'
down_revision = 'fcd73b904434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=50), nullable=False, server_default='TEMP_BATCH'))
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
