"""Add bulk operations fields with correct FK

Revision ID: c435fc4ba930
Revises: 
Create Date: 2025-07-21 13:12:49.423688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c435fc4ba930'
down_revision = 'add_course_end_date'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reschedule_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('original_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('original_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rescheduled_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['cancelled_by'], ['id'])

    with op.batch_alter_table('notice_distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notice_distributions_acknowledged'))
        batch_op.drop_index(batch_op.f('idx_notice_distributions_read'))
        batch_op.drop_index(batch_op.f('idx_notice_distributions_user'))
        batch_op.drop_constraint(batch_op.f('notice_distributions_notice_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_notice_user', ['notice_id', 'user_id'])

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_notices_category'))
        batch_op.drop_index(batch_op.f('idx_notices_created_at'))
        batch_op.drop_index(batch_op.f('idx_notices_created_by'))
        batch_op.drop_index(batch_op.f('idx_notices_priority'))
        batch_op.drop_index(batch_op.f('idx_notices_published'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_notices_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('idx_notices_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_notices_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_notices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_notices_category'), ['category'], unique=False)

    with op.batch_alter_table('notice_distributions', schema=None) as batch_op:
        batch_op.drop_constraint('unique_notice_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('notice_distributions_notice_id_user_id_key'), ['notice_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_notice_distributions_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_notice_distributions_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('idx_notice_distributions_acknowledged'), ['is_acknowledged'], unique=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rescheduled_by')
        batch_op.drop_column('rescheduled_at')
        batch_op.drop_column('original_time')
        batch_op.drop_column('original_date')
        batch_op.drop_column('reschedule_reason')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('template_name')

    # ### end Alembic commands ###
